/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alvan.novelist_app.UserInterfaceList;

import com.alvan.novelist_app.Database.KoneksiDatabase;
import com.alvan.novelist_app.Database.MemberClass;
import com.alvan.novelist_app.Database.SessionLogin;
import com.alvan.novelist_app.UserInterfaceList.Dialog.DetailBuku;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;

/**
 *
 * @author Nitro 5
 */
public class DashboardPage extends javax.swing.JFrame {


    String MemberId = SessionLogin.getUid();
    Boolean LoginStatus = SessionLogin.getStatusLogin();
    MemberClass member = MemberClass.getMeberDetail(MemberId);

    /**
     * Creates new form DashboardPage
     */
    public DashboardPage() {
        initComponents();
        setSize(new Dimension(1400, 800));
        setLocationRelativeTo(null);
        LblNamaUser.setText(member.getNama().toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDashboard = new javax.swing.JPanel();
        PanelSide = new javax.swing.JPanel();
        LabelLogoSide = new javax.swing.JLabel();
        LblProfile = new javax.swing.JLabel();
        jSeparatorProfile = new javax.swing.JSeparator();
        LblListPinjamanmu = new javax.swing.JLabel();
        jSeparatorListPinjamU = new javax.swing.JSeparator();
        BtnLogoutSide = new javax.swing.JButton();
        PanelNav = new javax.swing.JPanel();
        LblSelamat = new javax.swing.JLabel();
        LblNamaUser = new javax.swing.JLabel();
        PanelDashMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelListBuku = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelDashboard.setPreferredSize(new java.awt.Dimension(1400, 800));
        PanelDashboard.setLayout(null);

        PanelSide.setBackground(new java.awt.Color(255, 255, 255));

        LabelLogoSide.setIcon(new javax.swing.ImageIcon("D:\\Kuli\\s3\\pbo\\novelist_app\\src\\main\\java\\com\\alvan\\novelist_app\\AssetGambar\\Novelist-logos_transparent 4.png")); // NOI18N

        LblProfile.setBackground(new java.awt.Color(231, 146, 21));
        LblProfile.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblProfile.setForeground(new java.awt.Color(231, 146, 21));
        LblProfile.setText("Profile");

        LblListPinjamanmu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblListPinjamanmu.setForeground(new java.awt.Color(231, 146, 21));
        LblListPinjamanmu.setText("List Pinjaman");
        LblListPinjamanmu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblListPinjamanmuMouseClicked(evt);
            }
        });

        BtnLogoutSide.setBackground(new java.awt.Color(231, 146, 21));
        BtnLogoutSide.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnLogoutSide.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogoutSide.setText("Keluar");
        BtnLogoutSide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLogoutSideMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelSideLayout = new javax.swing.GroupLayout(PanelSide);
        PanelSide.setLayout(PanelSideLayout);
        PanelSideLayout.setHorizontalGroup(
            PanelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelLogoSide, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelSideLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(PanelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblListPinjamanmu)
                    .addComponent(LblProfile)
                    .addComponent(jSeparatorProfile)
                    .addComponent(jSeparatorListPinjamU)
                    .addComponent(BtnLogoutSide, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSideLayout.setVerticalGroup(
            PanelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSideLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LabelLogoSide, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(LblProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblListPinjamanmu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparatorListPinjamU, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 464, Short.MAX_VALUE)
                .addComponent(BtnLogoutSide, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        PanelDashboard.add(PanelSide);
        PanelSide.setBounds(0, 0, 260, 800);

        PanelNav.setBackground(new java.awt.Color(231, 146, 21));

        LblSelamat.setBackground(new java.awt.Color(255, 255, 255));
        LblSelamat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblSelamat.setForeground(new java.awt.Color(255, 255, 255));
        LblSelamat.setText("Halo : ");

        LblNamaUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblNamaUser.setForeground(new java.awt.Color(255, 255, 255));
        LblNamaUser.setText("Username");

        javax.swing.GroupLayout PanelNavLayout = new javax.swing.GroupLayout(PanelNav);
        PanelNav.setLayout(PanelNavLayout);
        PanelNavLayout.setHorizontalGroup(
            PanelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(LblSelamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblNamaUser)
                .addContainerGap(965, Short.MAX_VALUE))
        );
        PanelNavLayout.setVerticalGroup(
            PanelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNavLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(PanelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblSelamat)
                    .addComponent(LblNamaUser))
                .addGap(24, 24, 24))
        );

        PanelDashboard.add(PanelNav);
        PanelNav.setBounds(260, 0, 1140, 70);

        PanelDashMain.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 146, 21));
        jLabel1.setText("List Buku Yang Tersedia");

        TabelListBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 146, 21)));
        TabelListBuku.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TabelListBuku.setModel(DataListBukuTable());
        TabelListBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabelListBuku.setGridColor(new java.awt.Color(231, 146, 21));
        TabelListBuku.setRowHeight(50);
        TabelListBuku.setSelectionBackground(new java.awt.Color(231, 146, 21));
        TabelListBuku.setUpdateSelectionOnSort(false);
        TabelListBuku.setVerifyInputWhenFocusTarget(false);
        TabelListBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelListBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelListBuku);
        TabelListBuku.getAccessibleContext().setAccessibleParent(PanelDashMain);

        javax.swing.GroupLayout PanelDashMainLayout = new javax.swing.GroupLayout(PanelDashMain);
        PanelDashMain.setLayout(PanelDashMainLayout);
        PanelDashMainLayout.setHorizontalGroup(
            PanelDashMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDashMainLayout.createSequentialGroup()
                .addContainerGap(431, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(426, 426, 426))
            .addGroup(PanelDashMainLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDashMainLayout.setVerticalGroup(
            PanelDashMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDashMainLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        PanelDashboard.add(PanelDashMain);
        PanelDashMain.setBounds(290, 100, 1060, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLogoutSideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogoutSideMouseClicked
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        loginForm.setLocationRelativeTo(null);
        dispose();
        SessionLogin.setStatusLogin(false);
        SessionLogin.setUid(null);

    }//GEN-LAST:event_BtnLogoutSideMouseClicked

    private void LblListPinjamanmuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblListPinjamanmuMouseClicked
        dispose();
        
        ListPeminjamanPage listPeminjamanPage = new ListPeminjamanPage();
        listPeminjamanPage.setVisible(true);
        listPeminjamanPage.setLocationRelativeTo(null);
    }//GEN-LAST:event_LblListPinjamanmuMouseClicked

    private void TabelListBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelListBukuMouseClicked
        int selectedRow = TabelListBuku.getSelectedRow();
        if (selectedRow != -1) {
            int id = (int) TabelListBuku.getValueAt(selectedRow, 0);
            System.out.println("ID: " + id);
            showBookDetailsDialog(id);
        }
    }//GEN-LAST:event_TabelListBukuMouseClicked

    private void showBookDetailsDialog(int bookId) {
        try {
            Connection connection = KoneksiDatabase.getConnection();
            String query = "SELECT * FROM buku WHERE id=?";
            PreparedStatement preparedStatement = connection.prepareStatement(query);
            preparedStatement.setInt(1, bookId);
            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                String judul = resultSet.getString("judul");
                double hargaPinjam = resultSet.getDouble("harga_pinjam");
                String pengarang = resultSet.getString("pengarang");
                int jumlahHalaman = resultSet.getInt("jumlah_halaman");
                String Gambar = resultSet.getString("gambar");
                String Penerbit = resultSet.getString("penerbit");
                String TahunTerbit = resultSet.getString("tahun_terbit");
                String Sinopsis = resultSet.getString("sinopsis");

                DetailBuku detailBuku = new DetailBuku();
                detailBuku.txtJudulBuku.setText(judul);
                detailBuku.txtHargaPinjam.setText(String.valueOf(hargaPinjam));
                detailBuku.txtPengarang.setText(pengarang);
                detailBuku.txtJumlahHalaman.setText(String.valueOf(jumlahHalaman));
                detailBuku.txtPenerbit.setText(Penerbit);
                detailBuku.txtTahunTerbit.setText(TahunTerbit);
                detailBuku.textareaSinopsis.setText(Sinopsis);

                URL url = new URL(Gambar);
                Image originalImage = ImageIO.read(url);
                int width = 230;
                int height = 380;
                Image scaledImage = originalImage.getScaledInstance(width, height, Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(scaledImage);
                detailBuku.GambarBuku.setIcon(icon);

                detailBuku.setVisible(true);
                detailBuku.setLocationRelativeTo(null);

                detailBuku.BtnTutupDetail.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        detailBuku.dispose();
                    }
                });
            }

            // Close the resources
            resultSet.close();
            preparedStatement.close();
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    private DefaultTableModel DataListBukuTable() {
        try {
            Connection connection = KoneksiDatabase.getConnection();
            String query = "SELECT * FROM buku";
            PreparedStatement preparedStatement = connection.prepareStatement(query);
            ResultSet resultSet = preparedStatement.executeQuery();

            DefaultTableModel model = new TidakBisaDiEdit();
            model.addColumn("No");
            model.addColumn("Judul");
            model.addColumn("Harga Pinjam");
            model.addColumn("Pengarang");
            model.addColumn("Jumlah Halaman");
            model.addColumn("Jumlah Stok");

            while (resultSet.next()) {
                model.addRow(new Object[]{
                        resultSet.getInt("id"),
                        resultSet.getString("judul"),
                        resultSet.getDouble("harga_pinjam"),
                        resultSet.getString("pengarang"),
                        resultSet.getInt("jumlah_halaman"),
                        resultSet.getInt("jumlah_stok")
                });
            }

            // Close the resources
            resultSet.close();
            preparedStatement.close();
            connection.close();

            return model;

        } catch (Exception e) {
            e.printStackTrace();
            return null; // or handle the exception according to your requirements
        }
    }

    private static class TidakBisaDiEdit extends DefaultTableModel {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardPage().setVisible(true);
            }
        });
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogoutSide;
    private javax.swing.JLabel LabelLogoSide;
    private javax.swing.JLabel LblListPinjamanmu;
    private javax.swing.JLabel LblNamaUser;
    private javax.swing.JLabel LblProfile;
    private javax.swing.JLabel LblSelamat;
    private javax.swing.JPanel PanelDashMain;
    private javax.swing.JPanel PanelDashboard;
    private javax.swing.JPanel PanelNav;
    private javax.swing.JPanel PanelSide;
    private javax.swing.JTable TabelListBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparatorListPinjamU;
    private javax.swing.JSeparator jSeparatorProfile;
    // End of variables declaration//GEN-END:variables
}
