/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alvan.novelist_app.UserInterfaceList;

import com.alvan.novelist_app.Database.MemberClass;
import com.alvan.novelist_app.Database.SessionLogin;
import java.awt.Dimension;

/**
 *
 * @author Acer
 */
public class ListPeminjamanPage extends javax.swing.JFrame {
    
    String MemberId = SessionLogin.getUid();
    Boolean LoginStatus = SessionLogin.getStatusLogin();
    MemberClass member = MemberClass.getMeberDetail(MemberId);
    
    /**
     * Creates new form ListPeminjamanPage
     */
    public ListPeminjamanPage() {
        initComponents();
        setSize(new Dimension(1400, 800));
        setLocationRelativeTo(null);
        LblNamaUser.setText(member.getNama().toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPeminjaman = new javax.swing.JPanel();
        PanelSide = new javax.swing.JPanel();
        LabelLogo = new javax.swing.JLabel();
        LabelProfile = new javax.swing.JLabel();
        jSeparatorProfile = new javax.swing.JSeparator();
        LabelListPinjam = new javax.swing.JLabel();
        jSeparatorListPinjam = new javax.swing.JSeparator();
        BtnLogoutSide = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        PanelNav = new javax.swing.JPanel();
        LabelSelamat = new javax.swing.JLabel();
        LblNamaUser = new javax.swing.JLabel();
        PanelPeminMain = new javax.swing.JPanel();
        LabelListPinjamMain = new javax.swing.JLabel();
        PanelTabel = new javax.swing.JScrollPane();
        TabelPinjam = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelPeminjaman.setPreferredSize(new java.awt.Dimension(1400, 800));
        PanelPeminjaman.setLayout(null);

        PanelSide.setBackground(new java.awt.Color(255, 255, 255));
        PanelSide.setPreferredSize(new java.awt.Dimension(260, 800));
        PanelSide.setLayout(null);

        LabelLogo.setIcon(new javax.swing.ImageIcon("D:\\Kuli\\s3\\pbo\\novelist_app\\src\\main\\java\\com\\alvan\\novelist_app\\AssetGambar\\Novelist-logos_transparent 4.png")); // NOI18N
        PanelSide.add(LabelLogo);
        LabelLogo.setBounds(6, 15, 246, 56);
        LabelLogo.getAccessibleContext().setAccessibleName("LabelLogo");
        LabelLogo.getAccessibleContext().setAccessibleDescription("");

        LabelProfile.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LabelProfile.setForeground(new java.awt.Color(231, 146, 21));
        LabelProfile.setText("Profile");
        LabelProfile.setPreferredSize(new java.awt.Dimension(50, 22));
        PanelSide.add(LabelProfile);
        LabelProfile.setBounds(45, 146, 170, 22);
        LabelProfile.getAccessibleContext().setAccessibleName("LabelProfil");

        PanelSide.add(jSeparatorProfile);
        jSeparatorProfile.setBounds(45, 174, 170, 10);

        LabelListPinjam.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LabelListPinjam.setForeground(new java.awt.Color(231, 146, 21));
        LabelListPinjam.setText("List Pinjaman");
        LabelListPinjam.setMaximumSize(new java.awt.Dimension(102, 22));
        LabelListPinjam.setMinimumSize(new java.awt.Dimension(102, 22));
        LabelListPinjam.setPreferredSize(new java.awt.Dimension(102, 22));
        PanelSide.add(LabelListPinjam);
        LabelListPinjam.setBounds(45, 202, 110, 22);

        jSeparatorListPinjam.setMinimumSize(new java.awt.Dimension(170, 10));
        PanelSide.add(jSeparatorListPinjam);
        jSeparatorListPinjam.setBounds(45, 236, 170, 10);
        jSeparatorListPinjam.getAccessibleContext().setAccessibleName("");

        BtnLogoutSide.setBackground(new java.awt.Color(231, 146, 21));
        BtnLogoutSide.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnLogoutSide.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogoutSide.setText("Keluar");
        BtnLogoutSide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLogoutSideMouseClicked(evt);
            }
        });
        PanelSide.add(BtnLogoutSide);
        BtnLogoutSide.setBounds(45, 710, 170, 35);

        BtnBack.setBackground(new java.awt.Color(231, 146, 21));
        BtnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBack.setForeground(new java.awt.Color(255, 255, 255));
        BtnBack.setText("Kembali");
        BtnBack.setMaximumSize(new java.awt.Dimension(74, 27));
        BtnBack.setMinimumSize(new java.awt.Dimension(74, 27));
        BtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBackMouseClicked(evt);
            }
        });
        PanelSide.add(BtnBack);
        BtnBack.setBounds(45, 650, 170, 35);

        PanelPeminjaman.add(PanelSide);
        PanelSide.setBounds(0, 0, 260, 800);

        PanelNav.setBackground(new java.awt.Color(231, 146, 21));
        PanelNav.setPreferredSize(new java.awt.Dimension(1140, 70));
        PanelNav.setLayout(null);

        LabelSelamat.setBackground(new java.awt.Color(255, 255, 255));
        LabelSelamat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelSelamat.setForeground(new java.awt.Color(255, 255, 255));
        LabelSelamat.setText("Halo :");
        LabelSelamat.setMaximumSize(new java.awt.Dimension(44, 20));
        LabelSelamat.setMinimumSize(new java.awt.Dimension(44, 20));
        LabelSelamat.setPreferredSize(new java.awt.Dimension(44, 20));
        PanelNav.add(LabelSelamat);
        LabelSelamat.setBounds(58, 26, 44, 20);

        LblNamaUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblNamaUser.setForeground(new java.awt.Color(255, 255, 255));
        LblNamaUser.setText("Username");
        PanelNav.add(LblNamaUser);
        LblNamaUser.setBounds(108, 26, 70, 20);

        PanelPeminjaman.add(PanelNav);
        PanelNav.setBounds(260, 0, 1140, 70);
        PanelNav.getAccessibleContext().setAccessibleName("PanelNav");

        PanelPeminMain.setBackground(new java.awt.Color(255, 255, 255));
        PanelPeminMain.setPreferredSize(new java.awt.Dimension(1060, 650));

        LabelListPinjamMain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelListPinjamMain.setForeground(new java.awt.Color(231, 146, 21));
        LabelListPinjamMain.setText("List Pinjaman");

        PanelTabel.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TabelPinjam.setAutoCreateRowSorter(true);
        TabelPinjam.setForeground(new java.awt.Color(231, 146, 21));
        TabelPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TabelPinjam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelTabel.setViewportView(TabelPinjam);

        javax.swing.GroupLayout PanelPeminMainLayout = new javax.swing.GroupLayout(PanelPeminMain);
        PanelPeminMain.setLayout(PanelPeminMainLayout);
        PanelPeminMainLayout.setHorizontalGroup(
            PanelPeminMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPeminMainLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(PanelPeminMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelListPinjamMain))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        PanelPeminMainLayout.setVerticalGroup(
            PanelPeminMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPeminMainLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(LabelListPinjamMain)
                .addGap(18, 18, 18)
                .addComponent(PanelTabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        PanelPeminjaman.add(PanelPeminMain);
        PanelPeminMain.setBounds(290, 100, 1060, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelPeminjaman.getAccessibleContext().setAccessibleName("PanelPeminjaman");
        PanelPeminjaman.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBackMouseClicked
        dispose();
        
        DashboardPage dashboardPage = new DashboardPage();
        dashboardPage.setVisible(true);
        dashboardPage.setLocationRelativeTo(null);
    }//GEN-LAST:event_BtnBackMouseClicked

    private void BtnLogoutSideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogoutSideMouseClicked
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        loginForm.setLocationRelativeTo(null);
        dispose();
        SessionLogin.setStatusLogin(false);
        SessionLogin.setUid(null);
    }//GEN-LAST:event_BtnLogoutSideMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListPeminjamanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListPeminjamanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListPeminjamanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListPeminjamanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListPeminjamanPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnLogoutSide;
    private javax.swing.JLabel LabelListPinjam;
    private javax.swing.JLabel LabelListPinjamMain;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel LabelProfile;
    private javax.swing.JLabel LabelSelamat;
    private javax.swing.JLabel LblNamaUser;
    private javax.swing.JPanel PanelNav;
    private javax.swing.JPanel PanelPeminMain;
    private javax.swing.JPanel PanelPeminjaman;
    private javax.swing.JPanel PanelSide;
    private javax.swing.JScrollPane PanelTabel;
    private javax.swing.JTable TabelPinjam;
    private javax.swing.JSeparator jSeparatorListPinjam;
    private javax.swing.JSeparator jSeparatorProfile;
    // End of variables declaration//GEN-END:variables
}
