/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alvan.novelist_app.UserInterfaceList;

import java.awt.Dimension;

/**
 *
 * @author Nitro 5
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        setSize(new Dimension(1400, 800));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLoginUtama = new javax.swing.JPanel();
        PanelLoginKiri = new javax.swing.JPanel();
        LabelLogoLogin = new javax.swing.JLabel();
        PanelKananLogin = new javax.swing.JPanel();
        LabelMasuk = new javax.swing.JLabel();
        SeparatorMasuk = new javax.swing.JSeparator();
        LabelEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        LabelPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        BtnMasuk = new javax.swing.JButton();
        LabelDaftar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Login"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setResizable(false);

        PanelLoginUtama.setPreferredSize(new java.awt.Dimension(1400, 800));
        PanelLoginUtama.setLayout(null);

        PanelLoginKiri.setBackground(new java.awt.Color(231, 146, 21));
        PanelLoginKiri.setPreferredSize(new java.awt.Dimension(700, 800));

        LabelLogoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/alvan/novelist_app/AssetGambar/Novelist-logos_white 1.png"))); // NOI18N
        LabelLogoLogin.setLabelFor(PanelLoginKiri);

        javax.swing.GroupLayout PanelLoginKiriLayout = new javax.swing.GroupLayout(PanelLoginKiri);
        PanelLoginKiri.setLayout(PanelLoginKiriLayout);
        PanelLoginKiriLayout.setHorizontalGroup(
            PanelLoginKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelLogoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        PanelLoginKiriLayout.setVerticalGroup(
            PanelLoginKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginKiriLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(LabelLogoLogin)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        PanelLoginUtama.add(PanelLoginKiri);
        PanelLoginKiri.setBounds(0, 0, 700, 800);

        PanelKananLogin.setBackground(new java.awt.Color(255, 255, 255));
        PanelKananLogin.setPreferredSize(new java.awt.Dimension(700, 800));

        LabelMasuk.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        LabelMasuk.setForeground(new java.awt.Color(231, 146, 21));
        LabelMasuk.setText("Masuk");

        SeparatorMasuk.setBackground(new java.awt.Color(255, 255, 255));
        SeparatorMasuk.setForeground(new java.awt.Color(153, 153, 153));
        SeparatorMasuk.setAlignmentY(1.0F);

        LabelEmail.setBackground(new java.awt.Color(255, 255, 255));
        LabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelEmail.setForeground(new java.awt.Color(102, 102, 102));
        LabelEmail.setText("Email");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        txtEmail.setMargin(new java.awt.Insets(2, 3, 2, 6));

        LabelPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelPassword.setForeground(new java.awt.Color(102, 102, 102));
        LabelPassword.setText("Password");

        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        BtnMasuk.setBackground(new java.awt.Color(231, 146, 21));
        BtnMasuk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnMasuk.setForeground(new java.awt.Color(255, 255, 255));
        BtnMasuk.setText("Masuk");

        LabelDaftar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        LabelDaftar.setForeground(new java.awt.Color(231, 146, 21));
        LabelDaftar.setText("Daftar Akun?");

        javax.swing.GroupLayout PanelKananLoginLayout = new javax.swing.GroupLayout(PanelKananLogin);
        PanelKananLogin.setLayout(PanelKananLoginLayout);
        PanelKananLoginLayout.setHorizontalGroup(
            PanelKananLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKananLoginLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(PanelKananLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelPassword)
                    .addGroup(PanelKananLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKananLoginLayout.createSequentialGroup()
                            .addComponent(SeparatorMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKananLoginLayout.createSequentialGroup()
                            .addComponent(LabelMasuk)
                            .addGap(292, 292, 292)))
                    .addGroup(PanelKananLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LabelDaftar)
                        .addGroup(PanelKananLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelEmail)
                            .addGroup(PanelKananLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BtnMasuk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING))))))
        );
        PanelKananLoginLayout.setVerticalGroup(
            PanelKananLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKananLoginLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(LabelMasuk)
                .addGap(18, 18, 18)
                .addComponent(SeparatorMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(LabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(BtnMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelDaftar)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        PanelLoginUtama.add(PanelKananLogin);
        PanelKananLogin.setBounds(700, 0, 700, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelLoginUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelLoginUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Login");
        getAccessibleContext().setAccessibleDescription("");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMasuk;
    private javax.swing.JLabel LabelDaftar;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelLogoLogin;
    private javax.swing.JLabel LabelMasuk;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JPanel PanelKananLogin;
    private javax.swing.JPanel PanelLoginKiri;
    private javax.swing.JPanel PanelLoginUtama;
    private javax.swing.JSeparator SeparatorMasuk;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
