/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alvan.novelist_app.UserInterfaceList;

import com.alvan.novelist_app.Database.KoneksiDatabase;
import com.alvan.novelist_app.Database.PasswordHash;
import com.alvan.novelist_app.Database.SessionLogin;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Nitro 5
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        setSize(new Dimension(1400, 800));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLoginUtama = new javax.swing.JPanel();
        PanelLoginKiri = new javax.swing.JPanel();
        LabelLogoLogin = new javax.swing.JLabel();
        PanelKananLogin = new javax.swing.JPanel();
        LabelMasuk = new javax.swing.JLabel();
        SeparatorMasuk = new javax.swing.JSeparator();
        LabelEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        LabelPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        BtnMasuk = new javax.swing.JButton();
        LabelDaftar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Login"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setResizable(false);

        PanelLoginUtama.setPreferredSize(new java.awt.Dimension(1400, 800));
        PanelLoginUtama.setLayout(null);

        PanelLoginKiri.setBackground(new java.awt.Color(231, 146, 21));
        PanelLoginKiri.setPreferredSize(new java.awt.Dimension(700, 800));

        LabelLogoLogin.setLabelFor(PanelLoginKiri);

        javax.swing.GroupLayout PanelLoginKiriLayout = new javax.swing.GroupLayout(PanelLoginKiri);
        PanelLoginKiri.setLayout(PanelLoginKiriLayout);
        PanelLoginKiriLayout.setHorizontalGroup(
            PanelLoginKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelLogoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        PanelLoginKiriLayout.setVerticalGroup(
            PanelLoginKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginKiriLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(LabelLogoLogin)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        PanelLoginUtama.add(PanelLoginKiri);
        PanelLoginKiri.setBounds(0, 0, 700, 800);

        PanelKananLogin.setBackground(new java.awt.Color(255, 255, 255));
        PanelKananLogin.setPreferredSize(new java.awt.Dimension(700, 800));

        LabelMasuk.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        LabelMasuk.setForeground(new java.awt.Color(231, 146, 21));
        LabelMasuk.setText("Masuk");

        SeparatorMasuk.setBackground(new java.awt.Color(255, 255, 255));
        SeparatorMasuk.setForeground(new java.awt.Color(153, 153, 153));
        SeparatorMasuk.setAlignmentY(1.0F);

        LabelEmail.setBackground(new java.awt.Color(255, 255, 255));
        LabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelEmail.setForeground(new java.awt.Color(102, 102, 102));
        LabelEmail.setText("Email");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        txtEmail.setMargin(new java.awt.Insets(2, 3, 2, 6));
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        LabelPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelPassword.setForeground(new java.awt.Color(102, 102, 102));
        LabelPassword.setText("Password");

        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });

        BtnMasuk.setBackground(new java.awt.Color(231, 146, 21));
        BtnMasuk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnMasuk.setForeground(new java.awt.Color(255, 255, 255));
        BtnMasuk.setText("Masuk");
        BtnMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMasukMouseClicked(evt);
            }
        });
        BtnMasuk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnMasukKeyPressed(evt);
            }
        });

        LabelDaftar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        LabelDaftar.setForeground(new java.awt.Color(231, 146, 21));
        LabelDaftar.setText("Daftar Akun?");
        LabelDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelDaftarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelKananLoginLayout = new javax.swing.GroupLayout(PanelKananLogin);
        PanelKananLogin.setLayout(PanelKananLoginLayout);
        PanelKananLoginLayout.setHorizontalGroup(
            PanelKananLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKananLoginLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(PanelKananLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelPassword)
                    .addGroup(PanelKananLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKananLoginLayout.createSequentialGroup()
                            .addComponent(SeparatorMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKananLoginLayout.createSequentialGroup()
                            .addComponent(LabelMasuk)
                            .addGap(292, 292, 292)))
                    .addGroup(PanelKananLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LabelDaftar)
                        .addGroup(PanelKananLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelEmail)
                            .addGroup(PanelKananLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BtnMasuk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING))))))
        );
        PanelKananLoginLayout.setVerticalGroup(
            PanelKananLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKananLoginLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(LabelMasuk)
                .addGap(18, 18, 18)
                .addComponent(SeparatorMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(LabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(BtnMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelDaftar)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        PanelLoginUtama.add(PanelKananLogin);
        PanelKananLogin.setBounds(700, 0, 700, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelLoginUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelLoginUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Login");
        getAccessibleContext().setAccessibleDescription("");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelDaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelDaftarMouseClicked
        // TODO add your handling code here:
        DaftarForm registerForm = new DaftarForm();
        registerForm.setVisible(true);
        registerForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_LabelDaftarMouseClicked

    private void BtnMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMasukMouseClicked
        Connection connection = KoneksiDatabase.getConnection();

        String email = txtEmail.getText();
        String password = txtPassword.getText();

        if (email.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Email dan Password tidak boleh kosong!");
            resetForm();
        } else {
            try {
                // Check if the user with the given email exists
                String checkUserSql = "SELECT * FROM member WHERE email = ?";
                try (PreparedStatement checkMemberStatement = connection.prepareStatement(checkUserSql)) {
                    checkMemberStatement.setString(1, email);

                    try (ResultSet userResultSet = checkMemberStatement.executeQuery()) {
                        if (userResultSet.next()) {
                            String memberId = userResultSet.getString("id");
                            String hashedPasswordFromDB = userResultSet.getString("password");

                            PasswordHash passwordHash = new PasswordHash();

                            if (passwordHash.checkPassword(password, hashedPasswordFromDB)) {

                                SessionLogin.setUid(memberId);
                                SessionLogin.setStatusLogin(true);

                                javax.swing.JOptionPane.showMessageDialog(null, "Login berhasil!");
                                DashboardPage dashboardPage = new DashboardPage();
                                dashboardPage.setVisible(true);
                                dashboardPage.setLocationRelativeTo(null);
                                this.dispose();
                            } else {
                                javax.swing.JOptionPane.showMessageDialog(null, "Email atau Password salah!");
                                resetForm();
                            }
                        } else {
                            javax.swing.JOptionPane.showMessageDialog(null, "User tidak ditemukan!");
                            resetForm();
                        }
                    }
                }
            } catch (SQLException e) {
                e.printStackTrace(); // Log or handle the exception appropriately
                javax.swing.JOptionPane.showMessageDialog(null, "Terjadi kesalahan!");
            }
        }



    }//GEN-LAST:event_BtnMasukMouseClicked

    private void BtnMasukKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnMasukKeyPressed
        Connection connection = KoneksiDatabase.getConnection();

        String email = txtEmail.getText();
        String password = txtPassword.getText();

        if (email.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Email dan Password tidak boleh kosong!");
            resetForm();
        } else {
            try {
                // Check if the user with the given email exists
                String checkUserSql = "SELECT * FROM member WHERE email = ?";
                try (PreparedStatement checkMemberStatement = connection.prepareStatement(checkUserSql)) {
                    checkMemberStatement.setString(1, email);

                    try (ResultSet userResultSet = checkMemberStatement.executeQuery()) {
                        if (userResultSet.next()) {
                            String memberId = userResultSet.getString("id");
                            String hashedPasswordFromDB = userResultSet.getString("password");

                            PasswordHash passwordHash = new PasswordHash();

                            if (passwordHash.checkPassword(password, hashedPasswordFromDB)) {

                                SessionLogin.setUid(memberId);
                                SessionLogin.setStatusLogin(true);

                                javax.swing.JOptionPane.showMessageDialog(null, "Login berhasil!");
                                DashboardPage dashboardPage = new DashboardPage();
                                dashboardPage.setVisible(true);
                                dashboardPage.setLocationRelativeTo(null);
                                this.dispose();
                            } else {
                                javax.swing.JOptionPane.showMessageDialog(null, "Email atau Password salah!");
                                resetForm();
                            }
                        } else {
                            javax.swing.JOptionPane.showMessageDialog(null, "User tidak ditemukan!");
                            resetForm();
                        }
                    }
                }
            } catch (SQLException e) {
                e.printStackTrace(); // Log or handle the exception appropriately
                javax.swing.JOptionPane.showMessageDialog(null, "Terjadi kesalahan!");
            }
        }
        
        if(evt.getKeyCode ()== KeyEvent.VK_ENTER){
        BtnMasuk.doClick();
        }
    }//GEN-LAST:event_BtnMasukKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        if(evt.getKeyCode ()== KeyEvent.VK_ENTER){
        txtPassword.requestFocus();
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if(evt.getKeyCode ()== KeyEvent.VK_ENTER){
        BtnMasuk.requestFocus();
        }
    }//GEN-LAST:event_txtPasswordKeyPressed


    private void resetForm() {
        txtEmail.setText("");
        txtPassword.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMasuk;
    private javax.swing.JLabel LabelDaftar;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelLogoLogin;
    private javax.swing.JLabel LabelMasuk;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JPanel PanelKananLogin;
    private javax.swing.JPanel PanelLoginKiri;
    private javax.swing.JPanel PanelLoginUtama;
    private javax.swing.JSeparator SeparatorMasuk;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
