/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alvan.novelist_app.UserInterfaceList.Dialog;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Nitro 5
 */
public class DetailBuku extends javax.swing.JFrame {

    /**
     * Creates new form DetailBuku
     */
    public DetailBuku() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Detail Buku");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMainDetailBuku = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        GambarBuku = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        BtnTutupDetail = new javax.swing.JButton();
        BtnPinjamBuku = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtJudulBuku = new javax.swing.JTextField();
        txtPengarang = new javax.swing.JTextField();
        txtJumlahHalaman = new javax.swing.JTextField();
        txtTahunTerbit = new javax.swing.JTextField();
        txtPenerbit = new javax.swing.JTextField();
        txtHargaPinjam = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        textareaSinopsis = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelMainDetailBuku.setBackground(new java.awt.Color(255, 255, 255));
        PanelMainDetailBuku.setPreferredSize(new java.awt.Dimension(900, 600));
        PanelMainDetailBuku.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(231, 146, 21));
        jLabel2.setText("Detail Buku");
        PanelMainDetailBuku.add(jLabel2);
        jLabel2.setBounds(400, 10, 90, 30);

        jSeparator1.setPreferredSize(new java.awt.Dimension(700, 10));
        PanelMainDetailBuku.add(jSeparator1);
        jSeparator1.setBounds(60, 50, 760, 20);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GambarBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GambarBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        PanelMainDetailBuku.add(jPanel1);
        jPanel1.setBounds(60, 70, 230, 380);
        PanelMainDetailBuku.add(jSeparator2);
        jSeparator2.setBounds(60, 470, 770, 10);

        BtnTutupDetail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnTutupDetail.setForeground(new java.awt.Color(231, 146, 21));
        BtnTutupDetail.setText("Tutup");
        BtnTutupDetail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 146, 21)));
        PanelMainDetailBuku.add(BtnTutupDetail);
        BtnTutupDetail.setBounds(60, 490, 370, 40);

        BtnPinjamBuku.setBackground(new java.awt.Color(231, 146, 21));
        BtnPinjamBuku.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnPinjamBuku.setForeground(new java.awt.Color(255, 255, 255));
        BtnPinjamBuku.setText("Pinjam Buku Ini");
        PanelMainDetailBuku.add(BtnPinjamBuku);
        BtnPinjamBuku.setBounds(470, 490, 360, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Judul Buku");
        PanelMainDetailBuku.add(jLabel3);
        jLabel3.setBounds(340, 70, 110, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Pengarang");
        PanelMainDetailBuku.add(jLabel4);
        jLabel4.setBounds(340, 110, 100, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Jumlah Hamalan");
        PanelMainDetailBuku.add(jLabel5);
        jLabel5.setBounds(340, 150, 110, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Tahun Terbit");
        PanelMainDetailBuku.add(jLabel6);
        jLabel6.setBounds(340, 190, 120, 16);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Penerbit");
        PanelMainDetailBuku.add(jLabel7);
        jLabel7.setBounds(340, 230, 110, 16);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Harga Pinjam / 7 Hari");
        PanelMainDetailBuku.add(jLabel8);
        jLabel8.setBounds(340, 270, 140, 16);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Sinopisis");
        PanelMainDetailBuku.add(jLabel9);
        jLabel9.setBounds(340, 320, 110, 16);

        txtJudulBuku.setEditable(false);
        txtJudulBuku.setBackground(new java.awt.Color(255, 255, 255));
        txtJudulBuku.setBorder(null);
        PanelMainDetailBuku.add(txtJudulBuku);
        txtJudulBuku.setBounds(500, 70, 320, 16);

        txtPengarang.setEditable(false);
        txtPengarang.setBackground(new java.awt.Color(255, 255, 255));
        txtPengarang.setBorder(null);
        PanelMainDetailBuku.add(txtPengarang);
        txtPengarang.setBounds(500, 110, 320, 16);

        txtJumlahHalaman.setEditable(false);
        txtJumlahHalaman.setBackground(new java.awt.Color(255, 255, 255));
        txtJumlahHalaman.setBorder(null);
        PanelMainDetailBuku.add(txtJumlahHalaman);
        txtJumlahHalaman.setBounds(500, 150, 320, 16);

        txtTahunTerbit.setEditable(false);
        txtTahunTerbit.setBackground(new java.awt.Color(255, 255, 255));
        txtTahunTerbit.setBorder(null);
        PanelMainDetailBuku.add(txtTahunTerbit);
        txtTahunTerbit.setBounds(500, 190, 320, 16);

        txtPenerbit.setEditable(false);
        txtPenerbit.setBackground(new java.awt.Color(255, 255, 255));
        txtPenerbit.setBorder(null);
        PanelMainDetailBuku.add(txtPenerbit);
        txtPenerbit.setBounds(500, 230, 320, 16);

        txtHargaPinjam.setEditable(false);
        txtHargaPinjam.setBackground(new java.awt.Color(255, 255, 255));
        txtHargaPinjam.setBorder(null);
        txtHargaPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaPinjamActionPerformed(evt);
            }
        });
        PanelMainDetailBuku.add(txtHargaPinjam);
        txtHargaPinjam.setBounds(500, 270, 320, 16);

        textareaSinopsis.setEditable(false);
        textareaSinopsis.setBackground(new java.awt.Color(255, 255, 255));
        textareaSinopsis.setColumns(20);
        textareaSinopsis.setLineWrap(true);
        textareaSinopsis.setRows(5);
        textareaSinopsis.setBorder(null);
        textareaSinopsis.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(textareaSinopsis);

        PanelMainDetailBuku.add(jScrollPane2);
        jScrollPane2.setBounds(500, 310, 320, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelMainDetailBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelMainDetailBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHargaPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaPinjamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPinjamBuku;
    public javax.swing.JButton BtnTutupDetail;
    public javax.swing.JLabel GambarBuku;
    private javax.swing.JPanel PanelMainDetailBuku;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextArea textareaSinopsis;
    public javax.swing.JTextField txtHargaPinjam;
    public javax.swing.JTextField txtJudulBuku;
    public javax.swing.JTextField txtJumlahHalaman;
    public javax.swing.JTextField txtPenerbit;
    public javax.swing.JTextField txtPengarang;
    public javax.swing.JTextField txtTahunTerbit;
    // End of variables declaration//GEN-END:variables
}
